name: "Reportar un error"
description: "Informa sobre un error en el Code Cheat Sheet de Java"
title: "[BUG] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        ## ¡Gracias por ayudarnos a mejorar!
        Completa la siguiente información para describir el error de forma clara.

  - type: input
    id: error-section
    attributes:
      label: "¿En qué sección ocurre el error?"
      description: Por ejemplo, Condicionales, Bucles, Clases...
      placeholder: "Ejemplo: Condicionales"
    validations:
      required: true

  - type: textarea
    id: error-description
    attributes:
      label: "Descripción del error"
      description: Explica qué ocurre y qué esperabas que ocurriera.
      placeholder: Describe el error aquí...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: "Pasos para reproducirlo"
      description: Describe los pasos exactos para ver el error.
      placeholder: |
        1. Ir a '...'
        2. Hacer clic en '...'
        3. Ocurre el error...
    validations:
      required: false

  - type: textarea
    id: screenshot
    attributes:
      label: "Captura de pantalla (opcional)"
      description: Puedes arrastrar una imagen aquí si ayuda a ilustrar el error.
    validations:
      required: false
