blank_issues_enabled: false
contact_links:
  - name: "Otra consulta o comentario general"
    url: "https://github.com/JumpCraft08/Code-Cheat-Sheet/discussions"
    about: "Si tu comentario no encaja en los formularios anteriores, crea una discusión aquí."
